repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.0   # versión estable
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

  -   repo: local
      hooks:
        - id: check-name-type-conflicts
          name: Check for name-type conflicts
          entry: python taskflow_manager/test/check_field_conflicts.py
          language: system
          types: [python]